# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

matrix:
  include:
    - os: linux
      env: EXAMPLE=01-executable TOOLCHAIN=sanitize-thread CONFIG=Release

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  - pip3 install --user requests

  # Install dependencies (CMake, Android NDK)
  - POLLY_SOURCE_DIR="`pwd`"
  - python3 "${POLLY_SOURCE_DIR}/bin/install-ci-dependencies.py"

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"

  - echo 2 > /proc/sys/kernel/randomize_va_space

script:
  - >
    python3 "${POLLY_SOURCE_DIR}/bin/build.py"
    --home examples/${EXAMPLE}
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --clear
    --install
    --test

branches:
  except:
    - /^pr\..*/
